//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaRestaurant.API.Infrastructure.Localisations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PizzaRestaurant.API.Infrastructure.Localisations.ErrorMessages_en_US", typeof(ErrorMessages_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CityValidationError {
            get {
                return ResourceManager.GetString("CityValidationError", resourceCulture);
            }
        }
        
        internal static string CountryValidationError {
            get {
                return ResourceManager.GetString("CountryValidationError", resourceCulture);
            }
        }
        
        internal static string RegionValidationError {
            get {
                return ResourceManager.GetString("RegionValidationError", resourceCulture);
            }
        }
        
        internal static string DescriptionValidationError {
            get {
                return ResourceManager.GetString("DescriptionValidationError", resourceCulture);
            }
        }
        
        internal static string AddressIdValidationError {
            get {
                return ResourceManager.GetString("AddressIdValidationError", resourceCulture);
            }
        }
        
        internal static string PizzaIdValidationError {
            get {
                return ResourceManager.GetString("PizzaIdValidationError", resourceCulture);
            }
        }
        
        internal static string UserIdValidationError {
            get {
                return ResourceManager.GetString("UserIdValidationError", resourceCulture);
            }
        }
        
        internal static string PizzaNameValidationError {
            get {
                return ResourceManager.GetString("PizzaNameValidationError", resourceCulture);
            }
        }
        
        internal static string PriceValidationError {
            get {
                return ResourceManager.GetString("PriceValidationError", resourceCulture);
            }
        }
        
        internal static string CaloryCountValidationError {
            get {
                return ResourceManager.GetString("CaloryCountValidationError", resourceCulture);
            }
        }
        
        internal static string RankValidationError {
            get {
                return ResourceManager.GetString("RankValidationError", resourceCulture);
            }
        }
        
        internal static string FirstNameValidationError {
            get {
                return ResourceManager.GetString("FirstNameValidationError", resourceCulture);
            }
        }
        
        internal static string LastNameValidationError {
            get {
                return ResourceManager.GetString("LastNameValidationError", resourceCulture);
            }
        }
        
        internal static string PhoneNumberValidationError {
            get {
                return ResourceManager.GetString("PhoneNumberValidationError", resourceCulture);
            }
        }
        
        internal static string EmailValidationError {
            get {
                return ResourceManager.GetString("EmailValidationError", resourceCulture);
            }
        }
    }
}
